// ═══════════════════════════════════════════════════════
// BinAI — All Module Configs
// Each module defines its own visual identity here.
// ModuleShell injects these as CSS custom properties.
// ═══════════════════════════════════════════════════════
import type { ModuleConfig } from '@/types/module.types';

export const m01Config: ModuleConfig = {
  id: 'm01', number: 1,
  titleHe: 'מהו AI?',
  subtitleHe: 'הבסיס לכל מה שאחריו',
  cluster: 'foundation',
  colors: {
    primary:   '#0F6E56',
    accent:    '#EF9F27',
    bg:        '#F0FAF6',
    surface:   '#D8F0E8',
    text:      '#04342C',
    textMuted: '#2A7A6E',
  },
  visualStyle: 'tech',
  iconName: 'TbBrain',
  durationHours: 3,
  tagsHe: ['יסודות', 'בינה מלאכותית', 'פרומפטים', 'כלים'],
  openingQuestionHe: 'מה הדבר הכי מדהים שחשבת שAI יכול לעשות — שהתברר שהוא לא יכול?',
  artifactNameHe: 'מדיניות AI אישית — החוזה שלי עם הטכנולוגיה',
  isAvailable: true,
  sections: [
    { id: 'opening',     titleHe: 'פתיחה',              startMin: 0,   endMin: 15,  type: 'opening' },
    { id: 'theory',      titleHe: 'מה זה AI?',          startMin: 15,  endMin: 45,  type: 'theory' },
    { id: 'reverse',     titleHe: 'בלש הפרומפטים',     startMin: 45,  endMin: 70,  type: 'reverseEng' },
    { id: 'break',       titleHe: 'הפסקה',              startMin: 70,  endMin: 85,  type: 'break' },
    { id: 'practice',    titleHe: 'תרגול מודרך',        startMin: 85,  endMin: 115, type: 'practice' },
    { id: 'shared',      titleHe: 'פרויקט משותף',       startMin: 115, endMin: 145, type: 'shared' },
    { id: 'quiz',        titleHe: 'בחינון',              startMin: 145, endMin: 165, type: 'quiz' },
    { id: 'closing',     titleHe: 'סיכום ותיק עבודות', startMin: 165, endMin: 180, type: 'closing' },
  ],
};

export const m02Config: ModuleConfig = {
  id: 'm02', number: 2,
  titleHe: 'כרטיסי שיחה CBT',
  subtitleHe: 'AI ליצירת כלי תמיכה רגשית',
  cluster: 'pedagogical',
  colors: {
    primary:   '#2A7A6E',
    accent:    '#C9A84C',
    bg:        '#F7F4EE',
    surface:   '#E8F5F2',
    text:      '#0F4A42',
    textMuted: '#3D7A6E',
  },
  visualStyle: 'botanical',
  iconName: 'TbLeaf',
  durationHours: 3,
  tagsHe: ['CBT', 'כרטיסי שיחה', 'תמיכה רגשית', 'פרומפטים'],
  openingQuestionHe: 'ספר על שיחה עם תלמיד שהיית רוצה שהייתה מתנהלת אחרת',
  artifactNameHe: '6 כרטיסי שיחה CBT מותאמים אישית',
  isAvailable: true,
  sections: [
    { id: 'opening',     titleHe: 'פתיחה — גבעת חלפון', startMin: 0,   endMin: 15,  type: 'opening' },
    { id: 'theory',      titleHe: 'מהו CBT?',            startMin: 15,  endMin: 45,  type: 'theory' },
    { id: 'reverse',     titleHe: 'בלש הפרומפטים',      startMin: 45,  endMin: 70,  type: 'reverseEng' },
    { id: 'break',       titleHe: 'הפסקה',               startMin: 70,  endMin: 85,  type: 'break' },
    { id: 'practice',    titleHe: 'יצירת הכרטיסים',     startMin: 85,  endMin: 115, type: 'practice' },
    { id: 'shared',      titleHe: 'מאגר כרטיסים',        startMin: 115, endMin: 145, type: 'shared' },
    { id: 'quiz',        titleHe: 'בחינון',               startMin: 145, endMin: 165, type: 'quiz' },
    { id: 'closing',     titleHe: 'סיכום ותיק עבודות',  startMin: 165, endMin: 180, type: 'closing' },
  ],
};

export const m03Config: ModuleConfig = {
  id: 'm03', number: 3,
  titleHe: 'חומרי לימוד לתחום הדעת',
  subtitleHe: 'AI לכל מקצוע, כל גיל, כל נושא',
  cluster: 'pedagogical',
  colors: {
    primary:   '#185FA5',
    accent:    '#EF9F27',
    bg:        '#EEF5FF',
    surface:   '#D5E8FF',
    text:      '#042C53',
    textMuted: '#0C447C',
  },
  visualStyle: 'academic',
  iconName: 'TbBooks',
  durationHours: 3,
  tagsHe: ['חומרי לימוד', 'דפי עבודה', 'דיפרנציאציה', 'תחום הדעת'],
  openingQuestionHe: 'מה הכי גוזל לך זמן בהכנת חומרים לתלמידים?',
  artifactNameHe: 'חבילת חומרים מותאמת לנושא ספציפי בתחום שלי',
  isAvailable: false,
  sections: [
    { id: 'opening',  titleHe: 'פתיחה',           startMin: 0,   endMin: 15,  type: 'opening' },
    { id: 'theory',   titleHe: 'AI לכל מקצוע',   startMin: 15,  endMin: 45,  type: 'theory' },
    { id: 'reverse',  titleHe: 'בלש הפרומפטים',  startMin: 45,  endMin: 70,  type: 'reverseEng' },
    { id: 'break',    titleHe: 'הפסקה',           startMin: 70,  endMin: 85,  type: 'break' },
    { id: 'practice', titleHe: 'תרגול מודרך',     startMin: 85,  endMin: 115, type: 'practice' },
    { id: 'shared',   titleHe: 'בנק חומרים',      startMin: 115, endMin: 145, type: 'shared' },
    { id: 'quiz',     titleHe: 'בחינון',           startMin: 145, endMin: 165, type: 'quiz' },
    { id: 'closing',  titleHe: 'סיכום',            startMin: 165, endMin: 180, type: 'closing' },
  ],
};

export const m04Config: ModuleConfig = {
  id: 'm04', number: 4,
  titleHe: 'שיעורי חינוך',
  subtitleHe: 'AI לבניית שיעורי ערכים וחינוך',
  cluster: 'pedagogical',
  colors: {
    primary:   '#993C1D',
    accent:    '#0F6E56',
    bg:        '#FFF5F0',
    surface:   '#FFE8DF',
    text:      '#4A1B0C',
    textMuted: '#712B13',
  },
  visualStyle: 'community',
  iconName: 'TbUsersGroup',
  durationHours: 3,
  tagsHe: ['שיעורי חינוך', 'ערכים', 'דילמות', 'עיגול שיחה'],
  openingQuestionHe: 'מה הנושא שהכי קשה לך לבנות עליו שיעור חינוך מעניין?',
  artifactNameHe: 'תכנית שיעור חינוך מלאה לנושא שנבחר',
  isAvailable: false,
  sections: [
    { id: 'opening',  titleHe: 'פתיחה',              startMin: 0,   endMin: 15,  type: 'opening' },
    { id: 'theory',   titleHe: 'שיעור חינוך טוב',   startMin: 15,  endMin: 45,  type: 'theory' },
    { id: 'reverse',  titleHe: 'בלש הפרומפטים',     startMin: 45,  endMin: 70,  type: 'reverseEng' },
    { id: 'break',    titleHe: 'הפסקה',              startMin: 70,  endMin: 85,  type: 'break' },
    { id: 'practice', titleHe: 'בניית שיעור',        startMin: 85,  endMin: 115, type: 'practice' },
    { id: 'shared',   titleHe: 'בנק שיעורי חינוך',  startMin: 115, endMin: 145, type: 'shared' },
    { id: 'quiz',     titleHe: 'בחינון',              startMin: 145, endMin: 165, type: 'quiz' },
    { id: 'closing',  titleHe: 'סיכום',               startMin: 165, endMin: 180, type: 'closing' },
  ],
};

export const m05Config: ModuleConfig = {
  id: 'm05', number: 5,
  titleHe: 'חשיבה יצירתית',
  subtitleHe: 'AI כשותף לחשיבה מחוץ לקופסא',
  cluster: 'thinking',
  colors: {
    primary:   '#534AB7',
    accent:    '#D85A30',
    bg:        '#F5F3FF',
    surface:   '#E8E5FF',
    text:      '#26215C',
    textMuted: '#534AB7',
  },
  visualStyle: 'creative',
  iconName: 'TbSparkles',
  durationHours: 3,
  tagsHe: ['חשיבה יצירתית', 'Design Thinking', 'SCAMPER', 'חדשנות'],
  openingQuestionHe: 'אם יכולת להמציא משהו בלי מגבלות — מה הוא היה?',
  artifactNameHe: 'ערכת חשיבה יצירתית לכיתה שלי',
  isAvailable: false,
  sections: [
    { id: 'opening',  titleHe: 'פתיחה — ללא מגבלות',    startMin: 0,   endMin: 15,  type: 'opening' },
    { id: 'theory',   titleHe: 'יצירתיות ניתן ללמוד',   startMin: 15,  endMin: 45,  type: 'theory' },
    { id: 'reverse',  titleHe: 'בלש הפרומפטים',         startMin: 45,  endMin: 70,  type: 'reverseEng' },
    { id: 'break',    titleHe: 'הפסקה',                  startMin: 70,  endMin: 85,  type: 'break' },
    { id: 'practice', titleHe: 'תפוח → אסוציאציות → כסא', startMin: 85, endMin: 115, type: 'practice' },
    { id: 'shared',   titleHe: 'בנק שיעורים יצירתיים',  startMin: 115, endMin: 145, type: 'shared' },
    { id: 'quiz',     titleHe: 'בחינון',                  startMin: 145, endMin: 165, type: 'quiz' },
    { id: 'closing',  titleHe: 'סיכום',                   startMin: 165, endMin: 180, type: 'closing' },
  ],
};

export const m06Config: ModuleConfig = {
  id: 'm06', number: 6,
  titleHe: 'מטא-קוגניציה',
  subtitleHe: 'AI לפיתוח מודעות לחשיבה עצמית',
  cluster: 'thinking',
  colors: {
    primary:   '#085041',
    accent:    '#534AB7',
    bg:        '#EDFAF5',
    surface:   '#D0F0E5',
    text:      '#04342C',
    textMuted: '#0F6E56',
  },
  visualStyle: 'reflective',
  iconName: 'TbBrainCircuit',
  durationHours: 3,
  tagsHe: ['מטא-קוגניציה', 'רפלקציה', 'יומן חשיבה', 'KWL'],
  openingQuestionHe: 'מתי בפעם האחרונה עצרת לחשוב — איך אני חושב על זה?',
  artifactNameHe: 'ערכת כלי מטא-קוגניציה לכיתה (3 פורמטים)',
  isAvailable: false,
  sections: [
    { id: 'opening',  titleHe: 'פתיחה',             startMin: 0,   endMin: 15,  type: 'opening' },
    { id: 'theory',   titleHe: 'מהי מטא-קוגניציה', startMin: 15,  endMin: 45,  type: 'theory' },
    { id: 'reverse',  titleHe: 'בלש הפרומפטים',    startMin: 45,  endMin: 70,  type: 'reverseEng' },
    { id: 'break',    titleHe: 'הפסקה',             startMin: 70,  endMin: 85,  type: 'break' },
    { id: 'practice', titleHe: 'תרגול מודרך',       startMin: 85,  endMin: 115, type: 'practice' },
    { id: 'shared',   titleHe: 'בנק שאלות',         startMin: 115, endMin: 145, type: 'shared' },
    { id: 'quiz',     titleHe: 'בחינון',             startMin: 145, endMin: 165, type: 'quiz' },
    { id: 'closing',  titleHe: 'סיכום',              startMin: 165, endMin: 180, type: 'closing' },
  ],
};

export const m07Config: ModuleConfig = {
  id: 'm07', number: 7,
  titleHe: 'תקשורת מקרבת',
  subtitleHe: 'NVC — AI לשיחות מחברות',
  cluster: 'sel',
  colors: {
    primary:   '#993556',
    accent:    '#534AB7',
    bg:        '#FFF0F5',
    surface:   '#FFD5E5',
    text:      '#4B1528',
    textMuted: '#72243E',
  },
  visualStyle: 'connective',
  iconName: 'TbHeartHandshake',
  durationHours: 3,
  tagsHe: ['NVC', 'תקשורת מקרבת', 'רוזנברג', 'שיחה', 'SEL'],
  openingQuestionHe: 'ספר על אי-הבנה עם תלמיד שחשבת "איך הגענו לזה?"',
  artifactNameHe: 'ערכת כרטיסי NVC — 4 שלבים × 4 סיטואציות',
  isAvailable: false,
  sections: [
    { id: 'opening',  titleHe: 'פתיחה',          startMin: 0,   endMin: 15,  type: 'opening' },
    { id: 'theory',   titleHe: 'ארבעת שלבי NVC', startMin: 15,  endMin: 45,  type: 'theory' },
    { id: 'reverse',  titleHe: 'בלש הפרומפטים',  startMin: 45,  endMin: 70,  type: 'reverseEng' },
    { id: 'break',    titleHe: 'הפסקה',           startMin: 70,  endMin: 85,  type: 'break' },
    { id: 'practice', titleHe: 'תרגול מודרך',     startMin: 85,  endMin: 115, type: 'practice' },
    { id: 'shared',   titleHe: 'מאגר כרטיסי NVC', startMin: 115, endMin: 145, type: 'shared' },
    { id: 'quiz',     titleHe: 'בחינון',           startMin: 145, endMin: 165, type: 'quiz' },
    { id: 'closing',  titleHe: 'סיכום',            startMin: 165, endMin: 180, type: 'closing' },
  ],
};

export const m08Config: ModuleConfig = {
  id: 'm08', number: 8,
  titleHe: 'אזורי ויסות',
  subtitleHe: 'AI לערכת ויסות רגשי לכיתה',
  cluster: 'sel',
  colors: {
    primary:   '#3B6D11',
    accent:    '#E24B4A',
    bg:        '#F0FAE8',
    surface:   '#D8F0C0',
    text:      '#173404',
    textMuted: '#27500A',
  },
  visualStyle: 'zonal',
  iconName: 'TbColorPicker',
  durationHours: 3,
  tagsHe: ['אזורי ויסות', 'ויסות רגשי', 'SEL', 'כלים'],
  openingQuestionHe: 'איפה אתה/ת ב"אזורים" כרגע? ולמה?',
  artifactNameHe: 'ערכת ויסות לכיתה: פוסטר + כרטיסי כלים',
  isAvailable: false,
  sections: [
    { id: 'opening',  titleHe: 'פתיחה',             startMin: 0,   endMin: 15,  type: 'opening' },
    { id: 'theory',   titleHe: 'ארבעת הצבעים',      startMin: 15,  endMin: 45,  type: 'theory' },
    { id: 'reverse',  titleHe: 'בלש הפרומפטים',     startMin: 45,  endMin: 70,  type: 'reverseEng' },
    { id: 'break',    titleHe: 'הפסקה',              startMin: 70,  endMin: 85,  type: 'break' },
    { id: 'practice', titleHe: 'בניית ארגז כלים',   startMin: 85,  endMin: 115, type: 'practice' },
    { id: 'shared',   titleHe: 'ארגז כלים קבוצתי',  startMin: 115, endMin: 145, type: 'shared' },
    { id: 'quiz',     titleHe: 'בחינון',              startMin: 145, endMin: 165, type: 'quiz' },
    { id: 'closing',  titleHe: 'סיכום',               startMin: 165, endMin: 180, type: 'closing' },
  ],
};

export const m09Config: ModuleConfig = {
  id: 'm09', number: 9,
  titleHe: 'מנטליות צמיחה',
  subtitleHe: 'AI לשפת עידוד וצמיחה',
  cluster: 'sel',
  colors: {
    primary:   '#854F0B',
    accent:    '#3B6D11',
    bg:        '#FEF9EE',
    surface:   '#FAEEDA',
    text:      '#412402',
    textMuted: '#633806',
  },
  visualStyle: 'growth',
  iconName: 'TbPlant',
  durationHours: 3,
  tagsHe: ['מנטליות צמיחה', 'קרול דווק', 'משוב', 'עדיין', 'SEL'],
  openingQuestionHe: 'מה האמירה שאמרת לתלמיד שאתה/ת הכי מרוצה ממנה?',
  artifactNameHe: '12 כרטיסי "שפת הצמיחה" לכיתה',
  isAvailable: false,
  sections: [
    { id: 'opening',  titleHe: 'פתיחה',           startMin: 0,   endMin: 15,  type: 'opening' },
    { id: 'theory',   titleHe: 'Fixed vs Growth', startMin: 15,  endMin: 45,  type: 'theory' },
    { id: 'reverse',  titleHe: 'בלש הפרומפטים',  startMin: 45,  endMin: 70,  type: 'reverseEng' },
    { id: 'break',    titleHe: 'הפסקה',           startMin: 70,  endMin: 85,  type: 'break' },
    { id: 'practice', titleHe: 'כרטיסי "עדיין"',  startMin: 85,  endMin: 115, type: 'practice' },
    { id: 'shared',   titleHe: 'מדריך שפת הצמיחה', startMin: 115, endMin: 145, type: 'shared' },
    { id: 'quiz',     titleHe: 'בחינון',           startMin: 145, endMin: 165, type: 'quiz' },
    { id: 'closing',  titleHe: 'סיכום',            startMin: 165, endMin: 180, type: 'closing' },
  ],
};

export const m10Config: ModuleConfig = {
  id: 'm10', number: 10,
  titleHe: 'שיחות משקמות',
  subtitleHe: 'AI לשאלות עיגול ותרגול שיחה',
  cluster: 'sel',
  colors: {
    primary:   '#0C447C',
    accent:    '#0F6E56',
    bg:        '#EEF5FF',
    surface:   '#D5E8FF',
    text:      '#042C53',
    textMuted: '#185FA5',
  },
  visualStyle: 'circular',
  iconName: 'TbCircles',
  durationHours: 3,
  tagsHe: ['שיחות משקמות', 'עיגול שיחה', 'Restorative', 'SEL'],
  openingQuestionHe: 'ספר על קונפליקט בכיתה שנפתר בצורה שהפתיעה אותך',
  artifactNameHe: 'ערכת שיחות משקמות — שאלות עיגול + מדריך מנחה',
  isAvailable: false,
  sections: [
    { id: 'opening',  titleHe: 'פתיחה',              startMin: 0,   endMin: 15,  type: 'opening' },
    { id: 'theory',   titleHe: 'מהן שיחות משקמות',  startMin: 15,  endMin: 45,  type: 'theory' },
    { id: 'reverse',  titleHe: 'בלש הפרומפטים',     startMin: 45,  endMin: 70,  type: 'reverseEng' },
    { id: 'break',    titleHe: 'הפסקה',              startMin: 70,  endMin: 85,  type: 'break' },
    { id: 'practice', titleHe: 'בניית שאלות עיגול', startMin: 85,  endMin: 115, type: 'practice' },
    { id: 'shared',   titleHe: 'מאגר שאלות עיגול',  startMin: 115, endMin: 145, type: 'shared' },
    { id: 'quiz',     titleHe: 'בחינון',              startMin: 145, endMin: 165, type: 'quiz' },
    { id: 'closing',  titleHe: 'סיכום',               startMin: 165, endMin: 180, type: 'closing' },
  ],
};

// ── ALL MODULES (ordered) ────────────────────────────
export const ALL_MODULES: ModuleConfig[] = [
  m01Config, m02Config, m03Config, m04Config, m05Config,
  m06Config, m07Config, m08Config, m09Config, m10Config,
];

export const CLUSTERS = {
  foundation:   { titleHe: 'יסודות',               color: '#0F6E56' },
  pedagogical:  { titleHe: 'כלים פדגוגיים',         color: '#185FA5' },
  thinking:     { titleHe: 'חשיבה',                  color: '#534AB7' },
  sel:          { titleHe: 'למידה חברתית-רגשית',    color: '#993556' },
};
